server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
      - id: clients
        uri: https://localhost:8090/
        predicates:
        - Path/clientes/**
      - id: Products
        uri: https://localhost:8085/
        predicates:
        - Path/products/**
      - id: Assignment
        uri: https://localhost:8081/
        predicates:
        - Path/assignment/**
      - id: Movements
        uri: https://localhost:8082/
        predicates:
        - Path/movements/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTION

